### ISSUE TITLE
CTL Browser - Support Wallet Configured Networks

### ISSUE THREAD

**Issue by epiro-ps** [ArdanaLabs/cardano-app-template#10]
Currently we only support connecting to testnet for CTL browser apps. We want to make it so that the network the wallet is configured to is passed to CTL.

The following is how Nami supports setting the network:
<img width="399" alt="Screen Shot 2022-10-11 at 11 20 04 AM" src="https://user-images.githubusercontent.com/98818692/195132841-25a65abe-8cb6-45a0-bfb5-6df1caac1c1c.png">

This line of code is where we would need to support this:

https://github.com/ArdanaLabs/dUSD/compare/evan/try-mainnet?expand=1#diff-b57ecdd3fa818251d164204628a2c1c86fdaa01dc1b2de5174c800a7c497e302R87

**Comment by KelvinEthDev** [comment]
Have you able to resolved your issues

**Comment by leomayleomay** [comment]
@KelvinEthDev a [PR](https://github.com/ArdanaLabs/cardano-app-template/pull/11) filed ready to review
